export const FETCHING_FOLLOWING_USERS_STARTED =
  "FETCHING_FOLLOWING_USERS_STARTED";
export const FETCHING_FOLLOWING_USERS_COMPLETED =
  "FETCHING_FOLLOWING_USERS_COMPLETED";
export const FETCHING_FOLLOWING_USERS_FAILED =
  "FETCHING_FOLLOWING_USERS_FAILED";
export const FETCHING_FOLLOWER_USERS_STARTED =
  "FETCHING_FOLLOWER_USERS_STARTED";
export const FETCHING_FOLLOWER_USERS_COMPLETED =
  "FETCHING_FOLLOWER_USERS_COMPLETED";
export const FETCHING_FOLLOWER_USERS_FAILED = "FETCHING_FOLLOWER_USERS_FAILED";
export const AUTHENTICATION_IDENTITY_CLEARED =
  "AUTHENTICATION_IDENTITY_CLEARED";
export const UNFOLLOW_USER_STARTED = "UNFOLLOW_USER_STARTED";
export const UNFOLLOW_USER_COMPLETED = "UNFOLLOW_USER_COMPLETED";
export const UNFOLLOW_USER_FAILED = "UNFOLLOW_USER_FAILED";
export const FOLLOW_USER_STARTED = "FOLLOW_USER_STARTED";
export const FOLLOW_USER_COMPLETED = "FOLLOW_USER_COMPLETED";
export const FOLLOW_USER_FAILED = "FOLLOW_USER_FAILED";
