export const FETCHING_FOLLOWING_USERS_STARTED =
  "FETCHING_FOLLOWING_USERS_STARTED";
export const FETCHING_FOLLOWING_USERS_COMPLETED =
  "FETCHING_FOLLOWING_USERS_COMPLETED";
export const FETCHING_FOLLOWING_USERS_FAILED =
  "FETCHING_FOLLOWING_USERS_FAILED";
export const FETCHING_FOLLOWER_USERS_STARTED =
  "FETCHING_FOLLOWER_USERS_STARTED";
export const FETCHING_FOLLOWER_USERS_COMPLETED =
  "FETCHING_FOLLOWER_USERS_COMPLETED";
export const FETCHING_FOLLOWER_USERS_FAILED = "FETCHING_FOLLOWER_USERS_FAILED";
export const AUTHENTICATION_IDENTITY_CLEARED =
  "AUTHENTICATION_IDENTITY_CLEARED";
