export const FETCHING_FEED_TWEETS_STARTED = "FETCHING_FEED_TWEETS_STARTED";
export const FETCHING_TWEETS_COMPLETED = "FETCHING_TWEETS_COMPLETED";
export const FETCHING_TWEETS_FAILED = "FETCHING_TWEETS_FAILED";
export const POST_TWEET_STARTED = "POST_TWEET_STARTED";
export const POST_TWEET_COMPLETED = "POST_TWEET_COMPLETED";
export const POST_TWEET_FAILED = "POST_TWEET_FAILED";
export const RETWEET_COMPLETED = "RETWEET_COMPLETED";
export const FAV_TWEET_COMPLETED = "FAV_TWEET_COMPLETED";
export const AUTHENTICATION_IDENTITY_CLEARED =
  "AUTHENTICATION_IDENTITY_CLEARED";
