export const FETCHING_MY_TWEETS_STARTED = "FETCHING_MY_TWEETS_STARTED";
export const FETCHING_MY_TWEETS_COMPLETED = "FETCHING_MY_TWEETS_COMPLETED";
export const FETCHING_MY_TWEETS_FAILED = "FETCHING_MY_TWEETS_FAILED";
