export const CHANGE_PROFILE_NAVIGATION = "CHANGE_PROFILE_NAVIGATION";
export const AUTHENTICATION_IDENTITY_CLEARED =
  "AUTHENTICATION_IDENTITY_CLEARED";
export const FETCHING_FEED_TWEETS_STARTED = "FETCHING_FEED_TWEETS_STARTED";
