export const FETCH_RECOMMENDATIONS_STARTED = "FETCH_RECOMMENDATIONS_STARTED";
export const FETCH_RECOMMENDATIONS_COMPLETED =
  "FETCH_RECOMMENDATIONS_COMPLETED";
export const FETCH_RECOMMENDATIONS_FAILED = "FETCH_RECOMMENDATIONS_FAILED";
export const FOLLOW_USER_COMPLETED = "FOLLOW_USER_COMPLETED";
